version: '3.8'

services:
  backend:
    build:
      context: ./comparetify-backend
      dockerfile: Dockerfile.test
    container_name: comparetify-backend
    ports:
      - "5001:5000"
    volumes:
      - comparetify-backend:/app 
    networks:
      - comparetify-test

  frontend:
    build:
      context: ./comparetify-frontend
      dockerfile: Dockerfile
    container_name: comparetify-frontend
    ports:
      - "3001:3000"
    networks:
      - comparetify-test

  db:
    image: postgres:13
    container_name: comparetify-db
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data  # Volume untuk menyimpan data DB
    networks:
      - comparetify-test

networks:
  comparetify-test:
    driver: bridge

volumes:
  comparetify-backend:  # Deklarasi volume untuk backend
  db-data:              # Deklarasi volume untuk database
