version: '3.8'

services:
  backend:
    build:
      context: ./comparetify-backend
      dockerfile: Dockerfile.test
    container_name: comparetify-backend-test
    ports:
      - "5001:5000"
    volumes:
      - comparetify-backend:/app  # Gunakan volume bernama comparetify-backend
    networks:
      - comparetify-test

  frontend:
    build:
      context: ./comparetify-frontend
      dockerfile: Dockerfile
    container_name: comparetify-frontend-test
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5001
    networks:
      - comparetify-test

  db:
    image: postgres:13
    container_name: comparetify-db-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_database
    volumes:
      - db-data-test:/var/lib/postgresql/data
    networks:
      - comparetify-test

networks:
  comparetify-test:
    driver: bridge

volumes:
  comparetify-backend:  # Deklarasi volume untuk backend
  db-data-test:         # Deklarasi volume untuk database
