openapi: "3.0.0"
info:
  title: Sample API
  description: This is a sample API for demonstration purposes.
  version: "1.0.0"

servers:
  - url: "http://localhost:5000"
    description: Local server

paths:
  /hello:
    get:
      summary: Returns a greeting message
      description: A simple endpoint to test the API
      responses:
        200:
          description: A greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"

  /user/{user_id}:
    get:
      summary: Retrieve user information
      description: Get details of a user by their ID
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user
      responses:
        200:
          description: User data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  example:
                    user_id: 1
                    name: "John Doe"
                    email: "johndoe@example.com"
        404:
          description: User not found

  /user:
    post:
      summary: Create a new user
      description: Add a new user to the database
      requestBody:
        description: User data to be created
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
              required:
                - name
                - email
              example:
                name: "Jane Doe"
                email: "janedoe@example.com"
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  example:
                    user_id: 2
                    name: "Jane Doe"
                    email: "janedoe@example.com"
