FROM python:3.9-slim

# Create and set up a non-root user
RUN useradd -m appuser
WORKDIR /app
USER appuser

# Copy requirements first to leverage Docker layer caching
COPY --chown=appuser:appuser requirements.txt . 

# Install dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt --root-user-action=ignore

# Set environment variables
ENV FLASK_APP=app.main_test
ENV FLASK_ENV=development  

# Copy the rest of the application code
COPY --chown=appuser:appuser . .

# Expose the application's port
EXPOSE 5000

# Run tests by default in the test environment
CMD ["pytest", "comparetify-backend/app/main_test.py", "--disable-warnings"]
