FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

# RUN apt-get update && apt-get install -y libaio1
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

ENV FLASK_APP=app.main
ENV FLASK_ENV=development  

COPY . .

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
