FROM python:3.9-slim

# Buat user appuser dan set directory kerja
RUN useradd -m appuser
WORKDIR /app
USER appuser

# Salin requirements.txt dan instal dependensi
COPY --chown=appuser:appuser comparetify-backend/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Tambahkan ~/.local/bin ke PATH
ENV PATH="/home/appuser/.local/bin:${PATH}"

# Salin seluruh kode aplikasi
COPY --chown=appuser:appuser . .

# Perintah default untuk menjalankan tes
CMD ["pytest", "app/test_main.py", "--disable-warnings"]
